databases:
  - name: tvvqgbachma-db
    databaseName: tvvqgbachma
    user: tvvqgbachma
    plan: free
    ipAllowList: []

services:
  - type: web
    name: tvvqgbachma
    runtime: python
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_USERNAME
        value: ThucvatBM
      - key: ADMIN_PASSWORD
        value: Bachma123
      - key: DATABASE_URL
        fromDatabase:
          name: tvvqgbachma-db
          property: connectionString
